name: Generate ansible collection
description: Generate tarball name for collection to be built.

inputs:
  collections_paths:
    description: Path to the collection.
    required: true

runs:
  using: composite
  steps:
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install python required libraries
      run: pip install -U ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Run the test splitter
      run: python3 ${{ github.action_path }}/run.py '${{ inputs.collections_paths }}'
      shell: bash
